[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[metadata]
name = "bandai-scraper"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
    ".", "src",
]
